.TH "include/tuipp/widgets Directory Reference" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/widgets Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMarkupText\&.hpp\fP"
.br
.ti -1c
.RI "file \fBRule\&.hpp\fP"
.br
.ti -1c
.RI "file \fBText\&.hpp\fP"
.br
.in -1c
