.TH "include/tuipp Directory Reference" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolors\&.hpp\fP"
.br
.RI "Plenty of colors! "
.ti -1c
.RI "file \fBConsole\&.hpp\fP"
.br
.RI "A class that represent a console and some other console utility\&. "
.ti -1c
.RI "file \fBprint\&.hpp\fP"
.br
.RI "A utility to print text with markup support\&. "
.in -1c
