.TH "include/tuipp/widgets/styles Directory Reference" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/widgets/styles Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBackground\&.hpp\fP"
.br
.ti -1c
.RI "file \fBEffects\&.hpp\fP"
.br
.ti -1c
.RI "file \fBForeground\&.hpp\fP"
.br
.in -1c
