.TH "include/tuipp Directory Reference" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolors\&.hpp\fP"
.br
.RI "Plenty of colors! "
.ti -1c
.RI "file \fBConsole\&.hpp\fP"
.br
.RI "A class that represent a console with some useful utilities\&. "
.ti -1c
.RI "file \fBconsole_info\&.hpp\fP"
.br
.RI "A header that contains useful methods and types for getting the console informations\&. "
.in -1c
