.TH "include/tuipp/widgets/styles/Background.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/widgets/styles/Background.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::widgets\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::widgets::styles\fP"
.br
.RI "All the styles you want! "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBtuipp::widgets::styles::Background\fP { \fBtuipp::widgets::styles::NONE\fP, \fBtuipp::widgets::styles::RED\fP, \fBtuipp::widgets::styles::GREEN\fP, \fBtuipp::widgets::styles::GREY\fP, \fBtuipp::widgets::styles::BLUE\fP, \fBtuipp::widgets::styles::MAGENTA\fP, \fBtuipp::widgets::styles::YELLOW\fP, \fBtuipp::widgets::styles::CYAN\fP, \fBtuipp::widgets::styles::WHITE\fP, \fBtuipp::widgets::styles::BRIGHT_RED\fP, \fBtuipp::widgets::styles::BRIGHT_GREEN\fP, \fBtuipp::widgets::styles::BRIGHT_GREY\fP, \fBtuipp::widgets::styles::BRIGHT_BLUE\fP, \fBtuipp::widgets::styles::BRIGHT_MAGENTA\fP, \fBtuipp::widgets::styles::BRIGHT_YELLOW\fP, \fBtuipp::widgets::styles::BRIGHT_CYAN\fP, \fBtuipp::widgets::styles::BRIGHT_WHITE\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
