.TH "include/tuipp/styles/Border.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/styles/Border.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtuipp::styles::border::None\fP"
.br
.ti -1c
.RI "struct \fBtuipp::styles::border::Ascii\fP"
.br
.ti -1c
.RI "struct \fBtuipp::styles::border::Double\fP"
.br
.ti -1c
.RI "struct \fBtuipp::styles::border::Heavy\fP"
.br
.ti -1c
.RI "struct \fBtuipp::styles::border::Rounded\fP"
.br
.ti -1c
.RI "struct \fBtuipp::styles::border::Square\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::styles\fP"
.br
.RI "All the styles you want! "
.ti -1c
.RI "namespace \fBtuipp::styles::border\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBtuipp::styles::border::BorderType\fP { \fBtuipp::styles::border::NONE\fP, \fBtuipp::styles::border::ASCII\fP, \fBtuipp::styles::border::DOUBLE\fP, \fBtuipp::styles::border::HEAVY\fP, \fBtuipp::styles::border::ROUNDED\fP, \fBtuipp::styles::border::SQUARE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "TUIPP_NODISCARD std::string \fBtuipp::styles::border::get_part_from_border_type\fP (\fBBorderType\fP type, BorderParts part)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
