.TH "include/tuipp/colors.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/colors.hpp \- Plenty of colors!  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::colors\fP"
.br
.RI "Plenty of colors! "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::red\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::green\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::grey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::blue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::magenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::yellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::cyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::white\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_red\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_green\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_grey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_blue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_magenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_yellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_cyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::on_white\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_red\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_green\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_grey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_blue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_magenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_yellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_cyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bright_white\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::bold\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::underline\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::blink\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::italic\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBtuipp::colors::reset\fP (std::basic_ostream< CharT > &stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plenty of colors! 


.PP
\fBAuthor\fP
.RS 4
Giuliano De Amicis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
