.TH "include/tuipp/Console.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/Console.hpp \- A class that represent a console with some useful utilities\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtuipp::Console\fP"
.br
.RI "This is the class that represent a console\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class that represent a console with some useful utilities\&. 


.PP
\fBAuthor\fP
.RS 4
Giuliano De Amicis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
