.TH "include/tuipp/styles/Effects.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/styles/Effects.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::styles\fP"
.br
.RI "All the styles you want! "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBtuipp::styles::Effects\fP { \fBtuipp::styles::NONE\fP, \fBtuipp::styles::BOLD\fP, \fBtuipp::styles::UNDERLINE\fP, \fBtuipp::styles::BLINK\fP, \fBtuipp::styles::ITALIC\fP, \fBtuipp::styles::DIM\fP, \fBtuipp::styles::REVERSE\fP, \fBtuipp::styles::CONCEALED\fP, \fBtuipp::styles::STRIKE_THROUGH\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
