.TH "include/tuipp/styles/Justification.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/styles/Justification.hpp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::styles\fP"
.br
.RI "All the styles you want! "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBtuipp::styles::Justification\fP { \fBtuipp::styles::LEFT\fP, \fBtuipp::styles::CENTER\fP, \fBtuipp::styles::RIGHT\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
