.TH "include/tuipp/print.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/print.hpp \- A utility to print text with markup support\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBtuipp::println\fP (const Args &\&.\&.\&. content)"
.br
.RI "Print an output to the screen with a new line at the end (supports markup)\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBtuipp::print\fP (const Args &\&.\&.\&. content)"
.br
.RI "Print an output to the screen without a new line at the end (supports markup)\&. "
.in -1c
.SH "Detailed Description"
.PP 
A utility to print text with markup support\&. 

Example:

.PP
.PP
.nf
tuipp::println("[bold red]Hello, World![/]");

tuipp::print("[bold green]Hello, World![/]");
.fi
.PP

.PP
\fBAuthor\fP
.RS 4
Giuliano De Amicis 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
