.TH "include/tuipp/widgets/Rule.hpp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/tuipp/widgets/Rule.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtuipp::widgets::Rule\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtuipp\fP"
.br
.ti -1c
.RI "namespace \fBtuipp::widgets\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
