.TH "tuipp::widgets::Rule" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::Rule
.SH SYNOPSIS
.br
.PP
.PP
Inherits tuipp::widgets::IRenderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRule\fP (std::string content, \fBstyles::border::BorderType\fP border=\fBstyles::border::BorderType::SQUARE\fP)"
.br
.ti -1c
.RI "virtual void \fBrender\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfill_char\fP {}"
.br
.ti -1c
.RI "\fBstyles::Justification\fP \fBjustification\fP {}"
.br
.ti -1c
.RI "\fBstyles::Foreground\fP \fBcolor\fP {}"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tuipp::widgets::Rule::Rule (std::string content, \fBstyles::border::BorderType\fP border = \fR\fBstyles::border::BorderType::SQUARE\fP\fP)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void tuipp::widgets::Rule::render () const\fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstyles::Foreground\fP tuipp::widgets::Rule::color {}"

.SS "std::string tuipp::widgets::Rule::fill_char {}"

.SS "\fBstyles::Justification\fP tuipp::widgets::Rule::justification {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
