.TH "tuipp::widgets::styles::border" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::styles::border
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNone\fP"
.br
.ti -1c
.RI "struct \fBAscii\fP"
.br
.ti -1c
.RI "struct \fBDouble\fP"
.br
.ti -1c
.RI "struct \fBHeavy\fP"
.br
.ti -1c
.RI "struct \fBRounded\fP"
.br
.ti -1c
.RI "struct \fBSquare\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBorderType\fP { \fBNONE\fP, \fBASCII\fP, \fBDOUBLE\fP, \fBHEAVY\fP, \fBROUNDED\fP, \fBSQUARE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "TUIPP_NODISCARD std::string \fBget_part_from_border_type\fP (\fBBorderType\fP type, BorderParts part)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBtuipp::widgets::styles::border::BorderType\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BIASCII \fP
.TP
\f(BIDOUBLE \fP
.TP
\f(BIHEAVY \fP
.TP
\f(BIROUNDED \fP
.TP
\f(BISQUARE \fP
.SH "Function Documentation"
.PP 
.SS "TUIPP_NODISCARD std::string tuipp::widgets::styles::border::get_part_from_border_type (\fBBorderType\fP type, BorderParts part)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
