.TH "tuipp::widgets" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBstyles\fP"
.br
.RI "All the styles you want! "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMarkupText\fP"
.br
.RI "A widget for writing colorful text easily\&. "
.ti -1c
.RI "class \fBText\fP"
.br
.RI "Just normal text! "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
