.TH "tuipp::colors" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::colors \- Plenty of colors!  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBred\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBgreen\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBgrey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBblue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBmagenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fByellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBcyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBwhite\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_red\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_green\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_grey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_blue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_magenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_yellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_cyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBon_white\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_red\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_green\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_grey\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_blue\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_magenta\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_yellow\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_cyan\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbright_white\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBbold\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBunderline\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBblink\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBitalic\fP (std::basic_ostream< CharT > &stream)"
.br
.ti -1c
.RI "template<typename CharT> std::basic_ostream< CharT > & \fBreset\fP (std::basic_ostream< CharT > &stream)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plenty of colors! 
.SH "Function Documentation"
.PP 
.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::blink (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::blue (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bold (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_blue (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_cyan (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_green (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_grey (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_magenta (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_red (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_white (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::bright_yellow (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::cyan (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::green (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::grey (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::italic (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::magenta (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_blue (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_cyan (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_green (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_grey (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_magenta (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_red (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_white (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::on_yellow (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::red (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::reset (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::underline (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::white (std::basic_ostream< CharT > & stream)"

.SS "template<typename CharT> std::basic_ostream< CharT > & tuipp::colors::yellow (std::basic_ostream< CharT > & stream)"

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
