.TH "tuipp" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcolors\fP"
.br
.RI "Plenty of colors! "
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsole\fP"
.br
.RI "This is the class that represent a console\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBprintln\fP (const Args &\&.\&.\&. content)"
.br
.RI "Print an output to the screen with a new line at the end (supports markup)\&. "
.ti -1c
.RI "template<typename\&.\&.\&. Args> void \fBprint\fP (const Args &\&.\&.\&. content)"
.br
.RI "Print an output to the screen without a new line at the end (supports markup)\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename\&.\&.\&. Args> void tuipp::print (const Args &\&.\&.\&. content)"

.PP
Print an output to the screen without a new line at the end (supports markup)\&. 
.SS "Examples:"
.PP
.nf
tuipp::print("[bold green]Hello, World![/]");
tuipp::print(
"[green]This is green [bold]this is bold and green[/] this is still green[/]"
);
tuipp::print("[blue]Number of files: [/]", 10, "\&.");
tuipp::print("[green]This is green [bold]this is bold and green[reset] this is normal");
.fi
.PP
.SS "Styles:"
.IP "\(bu" 2
Foreground colors: \fRred\fP, \fRgreen\fP, \fRgrey\fP, \fRblue\fP, \fRmagenta\fP, \fRyellow\fP, \fRwhite\fP, \fRbright red\fP, \fRbright green\fP, \fRbright grey\fP, \fRbright blue\fP, \fRbright magenta\fP, \fRbright yellow\fP, \fRbright cyan\fP, \fRbright white\fP
.IP "\(bu" 2
Effects: \fRbold\fP, \fRunderline\fP, \fRblink\fP, \fRitalic\fP, \fRdim\fP, \fRstrikethrough\fP, \fRconceal\fP, \fRreverse\fP
.IP "\(bu" 2
Reset: \fR/\fP (for one style), \fRreset\fP (for all styles)
.IP "\(bu" 2
For the background colors just type: \fRon <color>\fP
.PP

.PP
.PP

.PP
You can also escape markup brackets using a backslash:

.PP
.PP
.nf
tuipp::print("\\[bold red]Hello, World!\\[/]");
.fi
.PP

.PP
.PP

.PP
It can also print iterables:

.PP
.PP
.nf
std::vector<int> vector{ { 1, 2, 3, 4, 5, 6 } };

tuipp::print(vector);
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIcontent\fP The items you want to print, they can be of any type and you can pass as many as you want\&. 
.RE
.PP

.SS "template<typename\&.\&.\&. Args> void tuipp::println (const Args &\&.\&.\&. content)"

.PP
Print an output to the screen with a new line at the end (supports markup)\&. 
.SS "Examples:"
.PP
.nf
tuipp::println("[bold green]Hello, World![/]");
tuipp::println(
"[green]This is green [bold]this is bold and green[/] this is still green[/]"
);
tuipp::println("[blue]Number of files: [/]", 10, "\&.");
tuipp::println("[green]This is green [bold]this is bold and green[reset] this is normal");
.fi
.PP
.SS "Styles:"
.IP "\(bu" 2
Foreground colors: \fRred\fP, \fRgreen\fP, \fRgrey\fP, \fRblue\fP, \fRmagenta\fP, \fRyellow\fP, \fRwhite\fP, \fRbright red\fP, \fRbright green\fP, \fRbright grey\fP, \fRbright blue\fP, \fRbright magenta\fP, \fRbright yellow\fP, \fRbright cyan\fP, \fRbright white\fP
.IP "\(bu" 2
Effects: \fRbold\fP, \fRunderline\fP, \fRblink\fP, \fRitalic\fP, \fRdim\fP, \fRstrikethrough\fP, \fRconceal\fP, \fRreverse\fP
.IP "\(bu" 2
Reset: \fR/\fP (for one style), \fRreset\fP (for all styles)
.IP "\(bu" 2
For the background colors just type: \fRon <color>\fP
.PP

.PP
.PP

.PP
You can also escape markup brackets using a backslash:

.PP
.PP
.nf
tuipp::println("\\[bold red]Hello, World!\\[/]");
.fi
.PP

.PP
.PP

.PP
It can also print iterables:

.PP
.PP
.nf
std::vector<int> vector{ { 1, 2, 3, 4, 5, 6 } };

tuipp::println(vector);
.fi
.PP

.PP
\fBParameters\fP
.RS 4
\fIcontent\fP The items you want to print, they can be of any type and you can pass as many as you want\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
