.TH "tuipp::console_info::TerminalSize" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::console_info::TerminalSize
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBwidth\fP {}"
.br
.ti -1c
.RI "std::size_t \fBheight\fP {}"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::size_t tuipp::console_info::TerminalSize::height {}"

.SS "std::size_t tuipp::console_info::TerminalSize::width {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
