.TH "tuipp::widgets::Text" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::Text \- Just normal text!  

.SH SYNOPSIS
.br
.PP
.PP
Inherits tuipp::widgets::IRenderable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (std::string content, \fBstyles::Justification\fP \fBjustification\fP=\fBstyles::Justification::LEFT\fP, \fBstyles::Foreground\fP \fBforeground\fP=\fBstyles::Foreground::NONE\fP, \fBstyles::Background\fP \fBbackground\fP=\fBstyles::Background::NONE\fP, std::vector< \fBstyles::Effects\fP > \fBeffects\fP={ \fBstyles::Effects::NONE\fP })"
.br
.ti -1c
.RI "virtual void \fBrender\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstyles::Foreground\fP \fBforeground\fP {}"
.br
.ti -1c
.RI "\fBstyles::Background\fP \fBbackground\fP {}"
.br
.ti -1c
.RI "std::vector< \fBstyles::Effects\fP > \fBeffects\fP {}"
.br
.ti -1c
.RI "\fBstyles::Justification\fP \fBjustification\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Just normal text! 


.SS "Examples of use"
.PP
.nf
// Create the widget:
auto text = tuipp::widgets::Text("Text widget!");

// 3 ways of rendering it:
tuipp::Console console;
console << text;

tuipp::Console::println(text);

text\&.render();
.fi
.PP

.PP
It also support styles:

.PP
.PP
.nf
auto colored_text =
  tuipp::widgets::Text("Colored text!",
                       tuipp::styles::Foreground::GREEN,
                       tuipp::styles::Background::GREY,
                       { tuipp::styles::Effects::BOLD });
.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tuipp::widgets::Text::Text (std::string content, \fBstyles::Justification\fP justification = \fR\fBstyles::Justification::LEFT\fP\fP, \fBstyles::Foreground\fP foreground = \fR\fBstyles::Foreground::NONE\fP\fP, \fBstyles::Background\fP background = \fR\fBstyles::Background::NONE\fP\fP, std::vector< \fBstyles::Effects\fP > effects = \fR{ \fBstyles::Effects::NONE\fP }\fP)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void tuipp::widgets::Text::render () const\fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstyles::Background\fP tuipp::widgets::Text::background {}"

.SS "std::vector<\fBstyles::Effects\fP> tuipp::widgets::Text::effects {}"

.SS "\fBstyles::Foreground\fP tuipp::widgets::Text::foreground {}"

.SS "\fBstyles::Justification\fP tuipp::widgets::Text::justification {}"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
