.TH "tuipp::widgets::styles" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::styles \- All the styles you want!  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBborder\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBBackground\fP { \fBNONE\fP, \fBRED\fP, \fBGREEN\fP, \fBGREY\fP, \fBBLUE\fP, \fBMAGENTA\fP, \fBYELLOW\fP, \fBCYAN\fP, \fBWHITE\fP, \fBBRIGHT_RED\fP, \fBBRIGHT_GREEN\fP, \fBBRIGHT_GREY\fP, \fBBRIGHT_BLUE\fP, \fBBRIGHT_MAGENTA\fP, \fBBRIGHT_YELLOW\fP, \fBBRIGHT_CYAN\fP, \fBBRIGHT_WHITE\fP }"
.br
.ti -1c
.RI "enum class \fBEffects\fP { \fBNONE\fP, \fBBOLD\fP, \fBUNDERLINE\fP, \fBBLINK\fP, \fBITALIC\fP, \fBDIM\fP, \fBREVERSE\fP, \fBCONCEALED\fP, \fBSTRIKE_THROUGH\fP }"
.br
.ti -1c
.RI "enum class \fBForeground\fP { \fBNONE\fP, \fBRED\fP, \fBGREEN\fP, \fBGREY\fP, \fBBLUE\fP, \fBMAGENTA\fP, \fBYELLOW\fP, \fBCYAN\fP, \fBWHITE\fP, \fBBRIGHT_RED\fP, \fBBRIGHT_GREEN\fP, \fBBRIGHT_GREY\fP, \fBBRIGHT_BLUE\fP, \fBBRIGHT_MAGENTA\fP, \fBBRIGHT_YELLOW\fP, \fBBRIGHT_CYAN\fP, \fBBRIGHT_WHITE\fP }"
.br
.ti -1c
.RI "enum class \fBJustification\fP { \fBLEFT\fP, \fBCENTER\fP, \fBRIGHT\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
All the styles you want! 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBtuipp::widgets::styles::Background\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BIRED \fP
.TP
\f(BIGREEN \fP
.TP
\f(BIGREY \fP
.TP
\f(BIBLUE \fP
.TP
\f(BIMAGENTA \fP
.TP
\f(BIYELLOW \fP
.TP
\f(BICYAN \fP
.TP
\f(BIWHITE \fP
.TP
\f(BIBRIGHT_RED \fP
.TP
\f(BIBRIGHT_GREEN \fP
.TP
\f(BIBRIGHT_GREY \fP
.TP
\f(BIBRIGHT_BLUE \fP
.TP
\f(BIBRIGHT_MAGENTA \fP
.TP
\f(BIBRIGHT_YELLOW \fP
.TP
\f(BIBRIGHT_CYAN \fP
.TP
\f(BIBRIGHT_WHITE \fP
.SS "enum class \fBtuipp::widgets::styles::Effects\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BIBOLD \fP
.TP
\f(BIUNDERLINE \fP
.TP
\f(BIBLINK \fP
.TP
\f(BIITALIC \fP
.TP
\f(BIDIM \fP
.TP
\f(BIREVERSE \fP
.TP
\f(BICONCEALED \fP
.TP
\f(BISTRIKE_THROUGH \fP
.SS "enum class \fBtuipp::widgets::styles::Foreground\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINONE \fP
.TP
\f(BIRED \fP
.TP
\f(BIGREEN \fP
.TP
\f(BIGREY \fP
.TP
\f(BIBLUE \fP
.TP
\f(BIMAGENTA \fP
.TP
\f(BIYELLOW \fP
.TP
\f(BICYAN \fP
.TP
\f(BIWHITE \fP
.TP
\f(BIBRIGHT_RED \fP
.TP
\f(BIBRIGHT_GREEN \fP
.TP
\f(BIBRIGHT_GREY \fP
.TP
\f(BIBRIGHT_BLUE \fP
.TP
\f(BIBRIGHT_MAGENTA \fP
.TP
\f(BIBRIGHT_YELLOW \fP
.TP
\f(BIBRIGHT_CYAN \fP
.TP
\f(BIBRIGHT_WHITE \fP
.SS "enum class \fBtuipp::widgets::styles::Justification\fP\fR [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILEFT \fP
.TP
\f(BICENTER \fP
.TP
\f(BIRIGHT \fP
.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
