.TH "tuipp::Console" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::Console
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBTerminalSize\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename\&.\&.\&. Args> \fBConsole\fP & \fBoperator<<\fP (const Args &\&.\&.\&. value)"
.br
.ti -1c
.RI "TUIPP_NODISCARD \fBTerminalSize\fP \fBget_terminal_size\fP ()"
.br
.ti -1c
.RI "\fBConsole\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tuipp::Console::Console ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "TUIPP_NODISCARD \fBTerminalSize\fP tuipp::Console::get_terminal_size ()"

.SS "template<typename\&.\&.\&. Args> \fBConsole\fP & tuipp::Console::operator<< (const Args &\&.\&.\&. value)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
