.TH "tuipp::styles::border::Rounded" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::styles::border::Rounded
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TUIPP_NODISCARD std::string \fBget_part\fP (BorderParts part)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "TUIPP_NODISCARD std::string tuipp::styles::border::Rounded::get_part (BorderParts part)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
