.TH "tuipp::widgets::styles::border::Border" 3 "Version 0.0.1" "TUI++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tuipp::widgets::styles::border::Border
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBtuipp::widgets::styles::border::Ascii\fP, \fBtuipp::widgets::styles::border::Double\fP, \fBtuipp::widgets::styles::border::Heavy\fP, \fBtuipp::widgets::styles::border::None\fP, \fBtuipp::widgets::styles::border::Rounded\fP, and \fBtuipp::widgets::styles::border::Square\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual TUIPP_NODISCARD std::string \fBget_part\fP (BorderParts part) const =0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "virtual TUIPP_NODISCARD std::string tuipp::widgets::styles::border::Border::get_part (BorderParts part) const\fR [pure virtual]\fP"

.PP
Implemented in \fBtuipp::widgets::styles::border::Ascii\fP, \fBtuipp::widgets::styles::border::Double\fP, \fBtuipp::widgets::styles::border::Heavy\fP, \fBtuipp::widgets::styles::border::None\fP, \fBtuipp::widgets::styles::border::Rounded\fP, and \fBtuipp::widgets::styles::border::Square\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for TUI++ from the source code\&.
